name: React Test
on:
    issues:
        types: [opened,closed]
    push:
        branches:
            - main
        paths-ignore: '.github\workflow'
    workflow_dispatch:
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Download Code
              uses: actions/checkout@v3
            - name: Installing Node latest version
              uses: actions/setup-node@v4
              with: 
                node-version: 18
            - name: Instaling Dependcies
              run: |
                cd ./"React Project"
                npm ci
            - name: Testing
              run: |
                cd ./"React Project"
                npm test
    
    deployment:
        outputs: 
          js_file_name: ${{steps.js.outputs.script-file}}
        runs-on: ubuntu-latest
        needs: [testing]
        steps:
            - name: Download Code
              uses: actions/checkout@v3
            - name: Installing Node latest version
              uses: actions/setup-node@v4
              with: 
                node-version: 18
            - name: Instaling Dependcies
              run: |
                cd ./"React Project"
                npm ci
            - name: Building Project
              run: |
                cd ./"React Project"
                npm run build
            - name: Publish JS file
              id: js
              run: |
                cd ./"React Project"
                find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT';'  
            - name: Deployment
              run: echo "Deploying Project to Production"
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: dist-files
                path: "React Project/dist"
    
    downloading:
      runs-on: ubuntu-latest
      needs: [deployment]
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v3
          with: 
            name: dist-files
        - name: Printing file name
          run: echo ${{needs.deployment.outputs.js_file_name}}


            


