name: React Test
on:
    issues:
        types: [opened,closed]
    push:
        branches:
            - main
        paths-ignore: '.github\workflow'
    workflow_dispatch:
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Download Code
              uses: actions/checkout@v3
            - name: Installing Node latest version
              uses: actions/setup-node@v4
              with: 
                node-version: 18
            - name: Instaling Dependcies
              run: |
                cd ./"React Project"
                npm ci
            - name: Testing
              run: |
                cd ./"React Project"
                npm test
    
    deployment:
        runs-on: ubuntu-latest
        needs: [testing]
        steps:
            - name: Download Code
              uses: actions/checkout@v3
            - name: Installing Node latest version
              uses: actions/setup-node@v4
              with: 
                node-version: 18
            - name: Instaling Dependcies
              run: |
                cd ./"React Project"
                npm ci
            - name: Building Project
              run: |
                cd ./"React Project"
                npm run build
            - name: Deployment
              run: echo "Deploying Project to Production"
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: dist-files
                path: dist
    
    downloading:
      runs-on: ubuntu-latest
      needs: [deployment]
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v3
          with: 
            name: dist-files


            


