name: React Test
on: push
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Download Code
              uses: actions/checkout@v3
            - name: Installing Node latest version
              uses: actions/setup-node@v4
              with: 
                node-version: 18
            - name: Instaling Dependcies
              run: |
                cd ./"React Project"
                npm ci
            - name: Testing
              run: npm test
            


